In [ ]:
#Date:22 Feb 2025
#print()use
print("welcome to codeswithcalvin.com")
print('welcome to cwcd.in')
print(78787454)

welcome to codeswithcalvin.com
welcome to cwcd.in
78787454


In [ ]:
#cat()
cat("Welcome to codeswithcalvin.com\n")
cat("my number is",675445)
#Example

cat("\nadd number",90+800)

Welcome to codeswithcalvin.com
my number is 675445
add number 890

In [ ]:
#variables

name<-"Frank"

age<-"18"

height<-"5.5"

cat("My name is:",name)

cat("\nMy height is:",height)

cat("\nMy Age is :",age)

My name is: Frank
My height is: 5.5
My Age is : 18

In [ ]:
a<-50

b<-45

c<-a+b

cat("result is:",c)

result is: 95

In [ ]:
#Date :25 Feb 2025

first_Name <-"Nishant"

roll_number <-"A234A"

#paste()

Information <- paste("Details:",first_name,roll_number)

print(Information)

#paste0()

Information<-paste0("Details:",first_name,roll_number)

print(Information)

[1] "Details: Nishant A234A"
[1] "Details:NishantA234A"


In [ ]:
#readline()
a<-as.integer(readline("Enter Java Marks out of 100 "))
b<-as.integer(readline(" Enter C++ Marks out of 100  "))
c<-as.integer(readline("Enter go Marks out of 100 "))
d<-as.integer(readline("Enter python Marks out of 100 "))
e<-as.integer(readline("Enter R Marks out of 100 "))

# Total
result = a+b+c+d+e

cat("\n Total =", result)

#percentage

result3= result*100/500

cat("\n your result is:",result3,"%")


Enter Java Marks out of 100 56
 Enter C++ Marks out of 100  50
Enter go Marks out of 100 60
Enter python Marks out of 100 75
Enter R Marks out of 100 23

 Total = 264
 your result is: 52.8 %

In [ ]:
#Date:27 Feb 2025
#Operator
#Arithmetic Operators

X<-25
Y<-20

X+Y

X-Y

X*Y

X%/%Y

X%%Y


[1] 45

[1] 5

[1] 500

[1] 1

[1] 5

In [ ]:
#Comparison Operators

52<25
25>10
65==65
65!=65
65<=65
65<=20
65<=65
65<=20

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

In [ ]:
#Logical Operators
#and&
  34<=45&45==25

  #or|
    34<=45|45==25

    #not!
    65!=65

[1] FALSE

[1] TRUE

[1] FALSE

In [ ]:
#Assignment Operators
X=20
print(X)

y<-10
print(y)

[1] 20
[1] 10


In [ ]:
data<-c(11,12,13,14,15,16)

12%in% data

21%in% data

[1] TRUE

[1] FALSE

In [ ]:
data=11:16
data

[1] 11 12 13 14 15 16

In [ ]:
#opearator
# find the odd number

a<-45
if(a%%2==0){
  print("a is even number")
}else{
  print("a is odd number")
}

[1] "a is odd number"


In [ ]:
#example odd&even number
b<-89
if(b%%2!=0){
  print("b is odd number")
}else{
  print("b is even number")
}

[1] "b is odd number"


In [ ]:
#R if..else
#find the smallest number
x<-45
y<-20
if(x<y){
  print("x is Smallest value")
}else{
  print("x is not Smallest value")
}




[1] "x is not Smallest value"


In [ ]:
#Date: 1 March 2025

# nested if else

Number1<-200
Number2<-800
Number3<-500

# find smallest number

#logic
#Number1<Number2
#Number1<Number3

#Number2<Number1
#Number2<Number3

#Number3<Number1
#Number3<Number2

if(Number1 <Number2&Number1 <Number3){
  print("Number1 is smallest.....")
}else if(Number2 < Number1 & Number2 <Number3){
  print("Number2 is smallest.....")
}else {
  print("Number3 is smallest.....")
}


[1] "Number1 is smallest....."


In [ ]:
#ifelse(test_expression,yes_expression,no_expression)

x=200
y=50

ifelse(x<y,"x is smallest","x is not smallest")

[1] "x is not smallest"

In [ ]:
#loop

for (i in 1:10){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [ ]:
for (i in 1:10){
  cat(i*2,'\n')
}

2 
4 
6 
8 
10 
12 
14 
16 
18 
20 


In [ ]:
#Task

# find odd number in 1 to 20


for(i in 1:20){
  if(i %% 2 !=0){
    cat(i,"odd",'\n')
  }else{
    cat(i,"even",'\n')
  }
}

1 odd 
2 even 
3 odd 
4 even 
5 odd 
6 even 
7 odd 
8 even 
9 odd 
10 even 
11 odd 
12 even 
13 odd 
14 even 
15 odd 
16 even 
17 odd 
18 even 
19 odd 
20 even 


In [ ]:
#Date : 4 March 2024

#While loop

a<-2
while(a<=20){
  print(a)
  a<-a+2
}

[1] 2
[1] 4
[1] 6
[1] 8
[1] 10
[1] 12
[1] 14
[1] 16
[1] 18
[1] 20


In [ ]:
#Repeat

count<-2
repeat{
  cat("Count",count,"\n")
  count<-count+2
  if(count>10){
    break
  }
}

Count 2 
Count 4 
Count 6 
Count 8 
Count 10 


In [ ]:
for(i in 1:10){
  if(i>7){
    break
  }else{
    print(i)
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7


In [ ]:
for(i in 1:10){
  if(i>7){
    next
  }else{
    print(i)
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7


In [ ]:
#Function
#Basic Function and Call the Function

info<-function(){
  cat("\nWelcome to Codes with Calvin")
  cat("\nwelcome to cwcd")
}

info()
info()


Welcome to Codes with Calvin
welcome to cwcd
Welcome to Codes with Calvin
welcome to cwcd

In [ ]:
#Bill

bill<-function (price,quantity,gst){
  total_amt<-price*quantity
  gst_amt<-total_amt*gst/100
  total_price<-total_amt+gst_amt

  cat("\n------Invoice--------\n")
  cat("\nPrice=",price,"/-")
  cat("\nQuantity",quantity,"nos")
  cat("\nTotal_Amount=",total_amt,"/-")
  cat("\nGST=",gst,"%")
  cat("\nGST_Amount=",gst_amt,"/-")
  cat("\nTotal_Price=",total_price,"/-")
}

In [ ]:
bill(100,6,6)
bill(1500,10,18)


------Invoice--------

Price= 100 /-
Quantity 6 nos
Total_Amount= 600 /-
GST= 6 %
GST_Amount= 36 /-
Total_Price= 636 /-
------Invoice--------

Price= 1500 /-
Quantity 10 nos
Total_Amount= 15000 /-
GST= 18 %
GST_Amount= 2700 /-
Total_Price= 17700 /-

In [ ]:
#function with arg..

add<-function(number1,number2){
  result<-number1+number2
  cat("\nResult<-",result)
}

In [ ]:
add(200,500)
add(700,1000)


Result<- 700
Result<- 1700

In [ ]:
#Date:6 March 2024

#function with return

numbers<-function(){
  return(1000)
}



In [ ]:
#get return value

x<-numbers()

print(x)

[1] 1000


In [ ]:
#function with return type with arg

add<-function(num1,num2){
  result<-num1+num2
  return(result)
}

print(add(100,200))
print(add(350,600))

[1] 300
[1] 950


In [ ]:
#string function

data1<-"Welcome to CodeswithCalvin.com"
print(nchar(data1))#count char

#Substring Extraction

substr(data1,12,26)

#String Manipulation
toupper(data1)

[1] 30


[1] "CodeswithCalvin"

[1] "WELCOME TO CODESWITHCALVIN.COM"

In [ ]:
data1<-"strawberry"
data2<-"Pineapple"

result<-data1<data2

print(result)

[1] FALSE


In [ ]:
#String interopolation

name<-"Calvin"
age<-21
height<-4.7
greeting<-sprintf("Hello,my name is %s and I am %d years old. and height %f",name,age,height)
cat("Greeting:",greeting,"\n")


Greeting: Hello,my name is Calvin and I am 21 years old. and height 4.700000 


In [ ]:
#Splitting and joining strings
text<-"strawberry,pineapple,cactus"
split_text<-strsplit(text,"")[[1]]
joined_text<-paste(split_text,collapse="")
cat("Joined text:",joined_text,"\n")

Joined text: strawberry,pineapple,cactus 


In [ ]:
#R Vectors

data<-c('Maths','English','Science','Social Studies')

data
print(data)
cat(data)

[1] "Maths"          "English"        "Science"        "Social Studies"

[1] "Maths"          "English"        "Science"        "Social Studies"
Maths English Science Social Studies

In [ ]:
#access data
data[3]
data[4]

[1] "Science"

[1] "Social Studies"

In [ ]:
#Date:8 March 2025

#Vectors

data=c(1,4,9,16)

sum(data)
length(data)
mean(data)
data^3

[1] 30

[1] 4

[1] 7.5

[1]    1   64  729 4096

In [ ]:
#matrix

numeric_matrix<-matrix(data=1:10,nrow=3,ncol=3)
numeric_matrix

Warning message in matrix(data = 1:10, nrow = 3, ncol = 3):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [ ]:
data=c(1,2,3,4,5,6,7,8,9)

numeric_matrix<-matrix(data=data,nrow=3,ncol=3)
numeric_matrix

print(numeric_matrix[2,2])

[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] 5


In [ ]:
#Price

data=c(1,2,3,4)

sum(data)
length(data)
mean(data)
data^3

[1] 10

[1] 4

[1] 2.5

[1]  1  8 27 64

In [ ]:
#Quantity

data=c(1,2,3,4)

sum(data)
length(data)
mean(data)
data^3

[1] 10

[1] 4

[1] 2.5

[1]  1  8 27 64

In [ ]:
#Total_Price

price<-c(1,2,3,4)
quantity<-c(1,2,3,4)

total_price<-price*quantity

cat("\ntotal_price=",total_price)


total_price= 1 4 9 16

In [ ]:
#Overall total_price

total_price<-c(1,4,9,16)

sum(total_price)
length(total_price)
mean(total_price)
data^3

[1] 30

[1] 4

[1] 7.5

[1]  1  8 27 64

In [ ]:
#matrix of price

numeric_matrix<-matrix(data=1:10,nrow=3,ncol=3)
numeric_matrix

Warning message in matrix(data = 1:10, nrow = 3, ncol = 3):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [ ]:
data<-c(1,2,3,4,5,6,7,8,9,10)

numeric_matrix<-matrix(data=data,nrow=3,ncol=3)
numeric_matrix

print(numeric_matrix[3,2])

Warning message in matrix(data = data, nrow = 3, ncol = 3):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] 6


In [ ]:
#matrix of quantity

numeric_matrix<-matrix(data=1:10,nrow=3,ncol=3)
numeric_matrix

Warning message in matrix(data = 1:10, nrow = 3, ncol = 3):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

In [ ]:
data<-c(1,2,3,4,5,6,7,8,9,10)

numeric_matrix<-matrix(data=data,nrow=3,ncol=3)
numeric_matrix

print(numeric_matrix[3,3])

Warning message in matrix(data = data, nrow = 3, ncol = 3):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3]
[1,] 1    4    7   
[2,] 2    5    8   
[3,] 3    6    9

[1] 9


In [ ]:
#matrix of overall total_price

total_price<-c(1,4,9,16)

numeric_matrix<-matrix(data=total_price,nrow=3,ncol=3)
numeric_matrix

print(numeric_matrix[2,1])

Warning message in matrix(data = total_price, nrow = 3, ncol = 3):
“data length [4] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3]
[1,] 1    16    9  
[2,] 4     1   16  
[3,] 9     4    1

[1] 4


In [ ]:
#Date:11 March 2025

#list

data=list(name="Frank",age=18,height=5.5,subject=c('Maths','English','Science','Social Studies'))
data

$name
[1] "Frank"

$age
[1] 18

$height
[1] 5.5

$subject
[1] "Maths"          "English"        "Science"        "Social Studies"

In [ ]:
#access data
data$name

[1] "Frank"

In [ ]:
data$subject
#access 3 subject
data$subject[4]

[1] "Maths"          "English"        "Science"        "Social Studies"

[1] "Social Studies"

In [ ]:
#using index

data[4]

data[[4]][2]

$subject
[1] "Maths"          "English"        "Science"        "Social Studies"

[1] "English"

In [ ]:
#update data

data$age=18
data

$name
[1] "Frank"

$age
[1] 18

$height
[1] 5.5

$subject
[1] "Maths"          "English"        "Science"        "Social Studies"

In [ ]:
#delete data

data$height = NULL
data

$name
[1] "Frank"

$age
[1] 18

$subject
[1] "Maths"          "English"        "Science"        "Social Studies"

In [ ]:
length(data)

names(data)

str(data)

[1] 3

[1] "name"    "age"     "subject"

List of 3
 $ name   : chr "Frank"
 $ age    : num 18
 $ subject: chr [1:4] "Maths" "English" "Science" "Social Studies"


In [ ]:
data_matrix<-matrix(1:10,nrow=3,ncol=4)
data_matrix

my_array<-array(data_matrix,dim=c(4,3,2))#c(row,col,number of array)
my_array

Warning message in matrix(1:10, nrow = 3, ncol = 4):
“data length [10] is not a sub-multiple or multiple of the number of rows [3]”


[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8     1  
[3,] 3    6    9     2

, , 1

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7    1
[4,]    4    8    2

, , 2

     [,1] [,2] [,3]
[1,]    1    5    9
[2,]    2    6   10
[3,]    3    7    1
[4,]    4    8    2

In [ ]:
my_array[20]

[1] 8

In [ ]:
#Creating a 3-dimensional array with dimension names
data_array<-array(1:10,dim=c(4,3,2),dimnames=list(c("A","F","G","J"),c("Q","R","S"),c("I","O")))
data_array

, , I

  Q R  S
A 1 5  9
F 2 6 10
G 3 7  1
J 4 8  2

, , O

  Q  R S
A 3  7 1
F 4  8 2
G 5  9 3
J 6 10 4

In [ ]:
dim(data_array)
dimnames(data_array)

[1] 4 3 2

[[1]]
[1] "A" "F" "G" "J"

[[2]]
[1] "Q" "R" "S"

[[3]]
[1] "I" "O"

In [ ]:
#dataframe

#Creating a dataframe
student_data<-data.frame(
  Name = c("Calvin","Frank","Akshay","Salman"),
Age = c(18, 20, 19, 25),
Grade = c("F","A","B","C"),
Passed = c(FALSE, TRUE, TRUE, TRUE)
)

print(student_data)


    Name Age Grade Passed
1 Calvin  18     F  FALSE
2  Frank  20     A   TRUE
3 Akshay  19     B   TRUE
4 Salman  25     C   TRUE


In [ ]:
student_data$Age[3]

[1] 19

In [ ]:
#Adding a new column
student_data$State<-c("Assam","Bihar","Telangana","Kerala")
print(student_data)

    Name Age Grade Passed     State
1 Calvin  18     F  FALSE     Assam
2  Frank  20     A   TRUE     Bihar
3 Akshay  19     B   TRUE Telangana
4 Salman  25     C   TRUE    Kerala


In [ ]:
names(student_data)
ncol(student_data)
nrow(student_data)
summary(student_data)

[1] "Name"   "Age"    "Grade"  "Passed" "State"

[1] 5

[1] 4

     Name                Age           Grade             Passed       
 Length:4           Min.   :18.00   Length:4           Mode :logical  
 Class :character   1st Qu.:18.75   Class :character   FALSE:1        
 Mode  :character   Median :19.50   Mode  :character   TRUE :3        
                    Mean   :20.50                                     
                    3rd Qu.:21.25                                     
                    Max.   :25.00                                     
    State          
 Length:4          
 Class :character  
 Mode  :character  
                   
                   
                   

In [106]:
#Exporting the data frame to a CSV file
write.csv(student_data,"data_frame.csv",row.names=TRUE)

In [2]:
# Importing data from a CSV file
df_imported <- read.csv("Chocolate Sales.csv")
# print(df_imported)
df = data.frame(df_imported)

names(df)
ncol(df)
nrow(df)
summary(df)

[1] "Sales.Person"  "Country"       "Product"       "Date"         
[5] "Amount"        "Boxes.Shipped"

[1] 6

[1] 1094

 Sales.Person         Country            Product              Date          
 Length:1094        Length:1094        Length:1094        Length:1094       
 Class :character   Class :character   Class :character   Class :character  
 Mode  :character   Mode  :character   Mode  :character   Mode  :character  
                                                                            
                                                                            
                                                                            
    Amount          Boxes.Shipped  
 Length:1094        Min.   :  1.0  
 Class :character   1st Qu.: 70.0  
 Mode  :character   Median :135.0  
                    Mean   :161.8  
                    3rd Qu.:228.8  
                    Max.   :709.0  

In [3]:
write.csv(df_imported,"data_frame.csv",row.names=TRUE)