In [ ]:
# Date : 20 Feb 2025
# print() use
print("welcome to codeswithpankaj.com")
print('welcome to cwpc.in')
print(78787454)

[1] "welcome to codeswithpankaj.com"
[1] "welcome to cwpc.in"
[1] 78787454


In [ ]:
# cat()
cat("Welcome to codeswithpankaj.com\n")
cat("my number is ",675445)
# Example

cat("\nadd number ",90+800)

Welcome to codeswithpankaj.com
my number is  675445
add number  890

In [ ]:
# variables

name <- "joy"
age <- 23
height <- 4.5
cat("My name is : ",name)
cat("\nMy height is : ",height)
cat("\nMy Age is : ",age)

My name is :  joy
My height is :  4.5
My Age is :  23

In [ ]:
a <- 10
b <- 40
c <- a + b
cat("result is : ",c)

result is :  50

In [ ]:
# Date : 25 Feb 2025


# paste0()
# paste()

first_name <- "Nishant"
last_name <- "jain"
# paste()
full_name <- paste("Your Name : ",first_name,last_name)

print(full_name)

# paste0()
full_name <- paste0("Your Name : ",first_name,last_name)

print(full_name)


[1] "Your Name :  Nishant jain"
[1] "Your Name : Nishantjain"


In [ ]:
# readline() # take userinput

name <- readline("Enter Your Name : ")
age <- readline("Enter Your age : ")
height <- readline("Enter Your height : ")

cat("Your Name is : ",name)
cat("\nYour Age is : ",age)
cat("\nYour height is : ",height)

Enter Your Name : Nishant
Enter Your age : 45
Enter Your height : 4.5
Your Name is :  Nishant
Your Age is :  45
Your height is :  4.5

In [ ]:
x <- readline("Enter Number 1 ")
y <- readline("Enter Number 2 ")

a <- as.integer(x)
b <- as.integer(y)

result = a + b

cat("\n your result is : ",result)

Enter Number 1 78
Enter Number 2 100

 your result is :  178

In [ ]:
x <- as.integer(readline("Enter Number 1 "))
y <- as.integer(readline("Enter Number 2 "))

result = x + y

cat("\n your result is : ",result)

Enter Number 1 45
Enter Number 2 60

 your result is :  105

In [ ]:
# task :
# input
# Enter your name : Nishant
# Enter your roll number : A234A

# Enter Java Marks out of 100 : 56
# Enter C++ Marks out of 100 : 50
# Enter go Marks out of 100 : 60
# Enter python Marks out of 100 : 75
# Enter R Marks out of 100 : 23

# Total = ?
# per% = ?

In [ ]:
# 27 Feb 2025
# Operator
# Arithmetic Operators:
x <- 564
y <- 23

x + y

x - y

x * y

x %/% y

x %% y

25%%2

[1] 587

[1] 541

[1] 12972

[1] 24

[1] 12

[1] 1

In [ ]:
# Comparison Operators

56 < 45
34 > 12
45 == 45
45 != 45
23 <= 23
20 <= 23
23 >= 23
20 >= 23




[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

In [ ]:
# logical Operator
# and &

34 < 45 & 45 == 10
#  t    &    f
34 < 45 & 45 != 10
# or |
34 < 45 | 45 == 10

# not !

67 != 67

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

In [ ]:
# Assignment Operators

x = 10
print(x)

y <- 20
print(y)

[1] 10
[1] 20


In [ ]:
data <- c(12,23,14,15,16,17)

12 %in% data

20 %in% data

[1] TRUE

[1] FALSE

In [ ]:
data = 11 : 20
data

[1] 11 12 13 14 15 16 17 18 19 20

In [ ]:
# R if..else
# find the smallest number
x <- 450
y <- 90
if(x < y)
{
  print("X is Smallest value")
  # t
}else
{
  #f
  print("X is not Smallest Value")
}

[1] "X is not Smallest Value"


In [ ]:
# Date : 1 March 2025

# nested if else

Number1 <- 1000
Number2 <- 200
Number3 <- 900

# find smallest Number

# logic
# Number1 < Number2
# Number1 < Number3

# Number2 < Number1
# Number2 < Number3

# Number3 < Number1
# Number3 < Number2

if(Number1 < Number2 & Number1 < Number3){
  print("Number1 is smallest .....")
}else if(Number2 < Number1 & Number2 < Number3){
  print("Number2 is smallest .....")
}else{
  print("Number3 is smallest .....")
}

[1] "Number2 is smallest ....."


In [ ]:
# ifelse(test_expression, yes_expression, no_expression)
x = 100
y = 90
ifelse(x < y,"X is smallest","X is not smallest")

[1] "X is not smallest"

In [ ]:
# loop

for(i in 1:10){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [ ]:
for(i in 1:10){
  cat(i*2,'\n')
}

2 
4 
6 
8 
10 
12 
14 
16 
18 
20 


In [ ]:
# 4 March 2025
# while loop

# start point
# end point
# print/output
# 1,2,3,4.. / 4,3,2,1..

a <- 1
while(a <= 10){
  print(a)
  a <- a + 1
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5
[1] 6
[1] 7
[1] 8
[1] 9
[1] 10


In [ ]:
count <- 1
repeat {
cat("Count:", count,"\n")
count <- count + 1
if (count > 5) {
  break # Terminate the loop when count reaches 5
}
}

Count: 1 
Count: 2 
Count: 3 
Count: 4 
Count: 5 


In [ ]:
for(i in 1:20){
  if(i > 5){
    break
  }else{
    print(i)
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [ ]:
for(i in 1:20){
  if(i > 5){
    next
  }else{
    print(i)
  }
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5


In [ ]:
# basic function
# function
# functionName <- function(){
#   task ....
# }

info <- function(){
  cat("\nWelcome to Codes with pankaj")
  cat("\nwelcome to cwpc")
}

# call the function
info()
info()


Welcome to Codes with pankaj
welcome to cwpc
Welcome to Codes with pankaj
welcome to cwpc

In [ ]:
# function with arg..

add <- function(number1,number2){
  result <- number1 + number2
  cat("\n Result <- ",result)
}

In [ ]:
add(124,456)
add(789,7000)


 Result <-  580
 Result <-  7789

In [ ]:
# bill

bill <- function(price,gst){
  gst_amount <- price*gst/100
  total_price <- price+gst_amount
  cat("\n--------bill--------\n")
  cat("\nAmount = ",price,"/-")
  cat("\nGST = ",gst,"%")
  cat("\nGST Amount  = ",gst_amount,"/-")
  cat("\nTotal Price (With GST)  = ",total_price,"/-")
}

In [ ]:
bill(1200,18)
bill(7800,2)
bill(9000,8)


--------bill--------

Amount =  1200 /-
GST =  18 %
GST Amount  =  216 /-
Total Price (With GST)  =  1416 /-
--------bill--------

Amount =  7800 /-
GST =  2 %
GST Amount  =  156 /-
Total Price (With GST)  =  7956 /-
--------bill--------

Amount =  9000 /-
GST =  8 %
GST Amount  =  720 /-
Total Price (With GST)  =  9720 /-

In [ ]:
# Date : 6 March 2025
# function with return

numbers <- function(){
  return(900)
}


In [ ]:
# get return value
x <- numbers()
print(x)

[1] 900


In [ ]:
# function with return type with arg

add <- function(num1,num2){
  result <- num1 + num2
  return(result)
}


print(add(1244,56))
print(add(56,100))

[1] 1300
[1] 156


In [ ]:
# string funtion

data1 <- "Welcome to Codeswihtpankaj.com"

print(nchar(data1)) # count char

# Substring Extraction

substr(data1,11,26)

# String Manipulation
tolower(data1)

[1] 30


[1] " Codeswihtpankaj"

[1] "welcome to codeswihtpankaj.com"

In [ ]:
data1 <- "apple"
data2 <- "Banana"
result <- data1 < data2
print(result)

[1] TRUE


In [ ]:
# String interpolation
name <- "Nishant"
age <- 12
height <- 4.5
greeting <- sprintf("Hello, my name is %s and I am %d years old. and height %f",name, age,height)
cat("Greeting:", greeting,"\n")

Greeting: Hello, my name is Nishant and I am 12 years old. and height 4.500000 


In [ ]:
# Splitting and joining strings
text <- "apple,banana,cherry"
split_text <- strsplit(text,",")[[1]]
joined_text <- paste(split_text, collapse =" ")
cat("Joined text:", joined_text,"\n")

Joined text: apple banana cherry 


In [ ]:
# R Vectors
data <- c('java','R','python','c++')

data
print(data)
cat(data)

[1] "java"   "R"      "python" "c++"

[1] "java"   "R"      "python" "c++"   
java R python c++

In [ ]:
# access data
data[2]
data[3]

[1] "R"

[1] "python"

In [ ]:
# Date : 8 March 2025

data = c(145,147,125,180,245)

sum(data)
length(data)
mean(data)
data^3

[1] 842

[1] 5

[1] 168.4

[1]  3048625  3176523  1953125  5832000 14706125

In [ ]:
numeric_matrix <- matrix(data = 21:29, nrow = 3, ncol = 3)
numeric_matrix

[,1] [,2] [,3]
[1,] 21   24   27  
[2,] 22   25   28  
[3,] 23   26   29

In [ ]:
data = c(22,33,44,55,66,77,88,66,77)
numeric_matrix <- matrix(data = data, nrow = 3, ncol = 3)
numeric_matrix

print(numeric_matrix[2,2])

[,1] [,2] [,3]
[1,] 22   55   88  
[2,] 33   66   66  
[3,] 44   77   77

[1] 66


In [ ]:
# date : 11 - 03 - 2025

# list

data = list(name="Nishant",age="23",height=4.5,subject=c("c++","java","python","R"))
data

$name
[1] "Nishant"

$age
[1] "23"

$height
[1] 4.5

$subject
[1] "c++"    "java"   "python" "R"

In [ ]:
# access data
data$name


[1] "Nishant"

In [ ]:
data$subject
# access 1 subject
data$subject[2]

[1] "c++"    "java"   "python" "R"

[1] "java"

In [ ]:
# using index
data[2]

data[[4]][2]

$age
[1] "23"

[1] "java"

In [ ]:
#update data

data$age = 31
data

$name
[1] "Nishant"

$age
[1] 31

$height
[1] 4.5

$subject
[1] "c++"    "java"   "python" "R"

In [ ]:
# delete data
data$height = NULL
data

$name
[1] "Nishant"

$age
[1] 31

$subject
[1] "c++"    "java"   "python" "R"

In [ ]:
length(data)

names(data)

str(data)

[1] 3

[1] "name"    "age"     "subject"

List of 3
 $ name   : chr "Nishant"
 $ age    : num 31
 $ subject: chr [1:4] "c++" "java" "python" "R"


In [ ]:
data_matrix <- matrix(1:12, nrow = 3, ncol = 4)
data_matrix

my_array <- array(data_matrix, dim = c(3, 4, 2)) # c(row,col,number of array)
my_array

[,1] [,2] [,3] [,4]
[1,] 1    4    7    10  
[2,] 2    5    8    11  
[3,] 3    6    9    12

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

, , 2

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12

In [ ]:
my_array[15]

[1] 3

In [ ]:
# Creating a 3-dimensional array with dimension names
data_array <- array(1:24, dim = c(3, 4, 2),
dimnames = list(c("A","B","C"),c("X","Y","Z","P"), c("M","N")))
data_array


, , M

  X Y Z  P
A 1 4 7 10
B 2 5 8 11
C 3 6 9 12

, , N

   X  Y  Z  P
A 13 16 19 22
B 14 17 20 23
C 15 18 21 24

In [ ]:
dim(data_array)
dimnames(data_array)

[1] 3 4 2

[[1]]
[1] "A" "B" "C"

[[2]]
[1] "X" "Y" "Z" "P"

[[3]]
[1] "M" "N"

In [ ]:
# dataframe

# Creating a data frame
student_data <- data.frame(
Name = c("Alice","Bob","Charlie","David"),
Age = c(25, 22, 24, 23),
Grade = c("A","B","A","C"),
Passed = c(TRUE, TRUE, TRUE, FALSE)
)

print(student_data)

     Name Age Grade Passed
1   Alice  25     A   TRUE
2     Bob  22     B   TRUE
3 Charlie  24     A   TRUE
4   David  23     C  FALSE


In [ ]:
student_data$Name[4]

[1] "David"

In [ ]:
# Adding a new column
student_data$City <- c("New York","Los Angeles","Chicago","Houston")
print(student_data)

     Name Age Grade Passed        City
1   Alice  25     A   TRUE    New York
2     Bob  22     B   TRUE Los Angeles
3 Charlie  24     A   TRUE     Chicago
4   David  23     C  FALSE     Houston


In [ ]:
names(student_data)
ncol(student_data)
nrow(student_data)
summary(student_data)

[1] "Name"   "Age"    "Grade"  "Passed" "City"

[1] 5

[1] 4

     Name                Age           Grade             Passed       
 Length:4           Min.   :22.00   Length:4           Mode :logical  
 Class :character   1st Qu.:22.75   Class :character   FALSE:1        
 Mode  :character   Median :23.50   Mode  :character   TRUE :3        
                    Mean   :23.50                                     
                    3rd Qu.:24.25                                     
                    Max.   :25.00                                     
     City          
 Length:4          
 Class :character  
 Mode  :character  
                   
                   
                   

In [ ]:
# Exporting the data frame to a CSV file
write.csv(student_data, "data_frame.csv", row.names = FALSE)

In [ ]:
# Importing data from a CSV file
df_imported <- read.csv("deliveries.csv")
# print(df_imported)

df = data.frame(df_imported)

names(df)
ncol(df)
nrow(df)
summary(df)

[1] "match_id"         "inning"           "batting_team"     "bowling_team"    
 [5] "over"             "ball"             "batter"           "bowler"          
 [9] "non_striker"      "batsman_runs"     "extra_runs"       "total_runs"      
[13] "extras_type"      "is_wicket"        "player_dismissed" "dismissal_kind"  
[17] "fielder"

[1] 17

[1] 260920

    match_id           inning      batting_team       bowling_team      
 Min.   : 335982   Min.   :1.000   Length:260920      Length:260920     
 1st Qu.: 548334   1st Qu.:1.000   Class :character   Class :character  
 Median : 980967   Median :1.000   Mode  :character   Mode  :character  
 Mean   : 907066   Mean   :1.484                                        
 3rd Qu.:1254066   3rd Qu.:2.000                                        
 Max.   :1426312   Max.   :6.000                                        
      over             ball           batter             bowler         
 Min.   : 0.000   Min.   : 1.000   Length:260920      Length:260920     
 1st Qu.: 4.000   1st Qu.: 2.000   Class :character   Class :character  
 Median : 9.000   Median : 4.000   Mode  :character   Mode  :character  
 Mean   : 9.198   Mean   : 3.624                                        
 3rd Qu.:14.000   3rd Qu.: 5.000                                        
 Max.   :19.000   Max.   :11.000                   